// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from model/chat.proto</summary>
  public static partial class ChatReflection {

    #region Descriptor
    /// <summary>File descriptor for model/chat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBtb2RlbC9jaGF0LnByb3RvEgJwYholZ2l0aHViLmNvbS8xNW1nYS9raXdp",
            "X3Rvb2wva2l3aS5wcm90byJSCgRDaGFuEgoKAmlkGAEgASgJEhsKCGNoYW5U",
            "eXBlGAIgASgOMgkucGIuRUNoYW4SDwoHbWVtYmVycxgDIAMoCToQ+ONJAYLk",
            "SQgKBgoEdHlwZSLMAQoDTXNnEgoKAmlkGAEgASgJEgwKBGNoSWQYAiABKAkS",
            "GwoIY2hhblR5cGUYAyABKA4yCS5wYi5FQ2hhbhILCgNtc2cYBCABKAwSEQoJ",
            "cHVibGlzaGVyGAUgASgJEhcKD3B1Ymxpc2hlckF2YXRhchgGIAEoCRITCgtw",
            "dWJsaXNoZXJJZBgHIAEoCTpA+ONJAYLkSQsKCQoHY2hhbl9pZILkSQ0KCwoJ",
            "cGxheWVyX2lkguRJGAoJCgdjaGFuX2lkCgsKCXBsYXllcl9pZCpUCgVFQ2hh",
            "bhIKCgZDaFRlYW0QABILCgdDaEdyb3VwEAESCgoGQ2hSb29tEAISCwoHQ2hT",
            "Y2VuZRADEgsKB0NoV29ybGQQBBIMCghDaFN5c3RlbRAFQhRaAy9wYqoCAlBi",
            "yt1JBhIEY2hhdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kiwi.KiwiReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.EChan), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Chan), global::Pb.Chan.Parser, new[]{ "Id", "ChanType", "Members" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Msg), global::Pb.Msg.Parser, new[]{ "Id", "ChId", "ChanType", "Msg_", "Publisher", "PublisherAvatar", "PublisherId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EChan {
    /// <summary>
    ///队伍
    /// </summary>
    [pbr::OriginalName("ChTeam")] ChTeam = 0,
    /// <summary>
    ///帮派组织
    /// </summary>
    [pbr::OriginalName("ChGroup")] ChGroup = 1,
    /// <summary>
    ///房间
    /// </summary>
    [pbr::OriginalName("ChRoom")] ChRoom = 2,
    /// <summary>
    ///地图
    /// </summary>
    [pbr::OriginalName("ChScene")] ChScene = 3,
    /// <summary>
    ///世界
    /// </summary>
    [pbr::OriginalName("ChWorld")] ChWorld = 4,
    /// <summary>
    ///系统
    /// </summary>
    [pbr::OriginalName("ChSystem")] ChSystem = 5,
  }

  #endregion

  #region Messages
  public sealed partial class Chan : pb::IMessage<Chan>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Chan> _parser = new pb::MessageParser<Chan>(() => new Chan());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Chan> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ChatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chan() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chan(Chan other) : this() {
      id_ = other.id_;
      chanType_ = other.chanType_;
      members_ = other.members_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chan Clone() {
      return new Chan(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chanType" field.</summary>
    public const int ChanTypeFieldNumber = 2;
    private global::Pb.EChan chanType_ = global::Pb.EChan.ChTeam;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.EChan ChanType {
      get { return chanType_; }
      set {
        chanType_ = value;
      }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_members_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> members_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Members {
      get { return members_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Chan);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Chan other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ChanType != other.ChanType) return false;
      if(!members_.Equals(other.members_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (ChanType != global::Pb.EChan.ChTeam) hash ^= ChanType.GetHashCode();
      hash ^= members_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ChanType != global::Pb.EChan.ChTeam) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChanType);
      }
      members_.WriteTo(output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ChanType != global::Pb.EChan.ChTeam) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChanType);
      }
      members_.WriteTo(ref output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (ChanType != global::Pb.EChan.ChTeam) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChanType);
      }
      size += members_.CalculateSize(_repeated_members_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Chan other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.ChanType != global::Pb.EChan.ChTeam) {
        ChanType = other.ChanType;
      }
      members_.Add(other.members_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            ChanType = (global::Pb.EChan) input.ReadEnum();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            ChanType = (global::Pb.EChan) input.ReadEnum();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Msg : pb::IMessage<Msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Msg> _parser = new pb::MessageParser<Msg>(() => new Msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ChatReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg(Msg other) : this() {
      id_ = other.id_;
      chId_ = other.chId_;
      chanType_ = other.chanType_;
      msg_ = other.msg_;
      publisher_ = other.publisher_;
      publisherAvatar_ = other.publisherAvatar_;
      publisherId_ = other.publisherId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg Clone() {
      return new Msg(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chId" field.</summary>
    public const int ChIdFieldNumber = 2;
    private string chId_ = "";
    /// <summary>
    ///chan id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChId {
      get { return chId_; }
      set {
        chId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chanType" field.</summary>
    public const int ChanTypeFieldNumber = 3;
    private global::Pb.EChan chanType_ = global::Pb.EChan.ChTeam;
    /// <summary>
    ///消息类型 1:文本 2:语音
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.EChan ChanType {
      get { return chanType_; }
      set {
        chanType_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int Msg_FieldNumber = 4;
    private pb::ByteString msg_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Msg_ {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "publisher" field.</summary>
    public const int PublisherFieldNumber = 5;
    private string publisher_ = "";
    /// <summary>
    ///消息发送者
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Publisher {
      get { return publisher_; }
      set {
        publisher_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "publisherAvatar" field.</summary>
    public const int PublisherAvatarFieldNumber = 6;
    private string publisherAvatar_ = "";
    /// <summary>
    ///消息发送者图标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublisherAvatar {
      get { return publisherAvatar_; }
      set {
        publisherAvatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "publisherId" field.</summary>
    public const int PublisherIdFieldNumber = 7;
    private string publisherId_ = "";
    /// <summary>
    ///消息发送者id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublisherId {
      get { return publisherId_; }
      set {
        publisherId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ChId != other.ChId) return false;
      if (ChanType != other.ChanType) return false;
      if (Msg_ != other.Msg_) return false;
      if (Publisher != other.Publisher) return false;
      if (PublisherAvatar != other.PublisherAvatar) return false;
      if (PublisherId != other.PublisherId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (ChId.Length != 0) hash ^= ChId.GetHashCode();
      if (ChanType != global::Pb.EChan.ChTeam) hash ^= ChanType.GetHashCode();
      if (Msg_.Length != 0) hash ^= Msg_.GetHashCode();
      if (Publisher.Length != 0) hash ^= Publisher.GetHashCode();
      if (PublisherAvatar.Length != 0) hash ^= PublisherAvatar.GetHashCode();
      if (PublisherId.Length != 0) hash ^= PublisherId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ChId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChId);
      }
      if (ChanType != global::Pb.EChan.ChTeam) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ChanType);
      }
      if (Msg_.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Msg_);
      }
      if (Publisher.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Publisher);
      }
      if (PublisherAvatar.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PublisherAvatar);
      }
      if (PublisherId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PublisherId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ChId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChId);
      }
      if (ChanType != global::Pb.EChan.ChTeam) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ChanType);
      }
      if (Msg_.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Msg_);
      }
      if (Publisher.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Publisher);
      }
      if (PublisherAvatar.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PublisherAvatar);
      }
      if (PublisherId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PublisherId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (ChId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChId);
      }
      if (ChanType != global::Pb.EChan.ChTeam) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChanType);
      }
      if (Msg_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Msg_);
      }
      if (Publisher.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Publisher);
      }
      if (PublisherAvatar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublisherAvatar);
      }
      if (PublisherId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublisherId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Msg other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.ChId.Length != 0) {
        ChId = other.ChId;
      }
      if (other.ChanType != global::Pb.EChan.ChTeam) {
        ChanType = other.ChanType;
      }
      if (other.Msg_.Length != 0) {
        Msg_ = other.Msg_;
      }
      if (other.Publisher.Length != 0) {
        Publisher = other.Publisher;
      }
      if (other.PublisherAvatar.Length != 0) {
        PublisherAvatar = other.PublisherAvatar;
      }
      if (other.PublisherId.Length != 0) {
        PublisherId = other.PublisherId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ChId = input.ReadString();
            break;
          }
          case 24: {
            ChanType = (global::Pb.EChan) input.ReadEnum();
            break;
          }
          case 34: {
            Msg_ = input.ReadBytes();
            break;
          }
          case 42: {
            Publisher = input.ReadString();
            break;
          }
          case 50: {
            PublisherAvatar = input.ReadString();
            break;
          }
          case 58: {
            PublisherId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ChId = input.ReadString();
            break;
          }
          case 24: {
            ChanType = (global::Pb.EChan) input.ReadEnum();
            break;
          }
          case 34: {
            Msg_ = input.ReadBytes();
            break;
          }
          case 42: {
            Publisher = input.ReadString();
            break;
          }
          case 50: {
            PublisherAvatar = input.ReadString();
            break;
          }
          case 58: {
            PublisherId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
