// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from model/player.proto</summary>
  public static partial class PlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for model/player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJtb2RlbC9wbGF5ZXIucHJvdG8SAnBiGhoxNW0uZ2FtZXMvdG9vbC92ZXJz",
            "ZS5wcm90byLCAgoGUGxheWVyEgoKAmlkGAEgASgJEg4KBnVzZXJJZBgCIAEo",
            "CRIMCgRuaWNrGAMgASgJEgwKBGhlcm8YBCABKAUSDgoGYXZhdGFyGAUgASgJ",
            "Eg4KBnRlYW1JZBgGIAEoCRIOCgZnZW5kZXIYByABKAUSIAoGc3RhdHVzGAgg",
            "ASgOMhAucGIuUGxheWVyU3RhdHVzEhIKCmxhc3RTaWduSW4YCSABKAMSEAoI",
            "bGFzdEFkZHIYCiABKAkSFAoMbGFzdEdhdGVOb2RlGAsgASgQOnL440kBguRJ",
            "DAoICgRuaWNrEAMQAYLkSQgKBgoEaGVyb4LkSQoKCAoGc3RhdHVzguRJEAoO",
            "CgxsYXN0X3NpZ25faW6C5EkNCgsKCWxhc3RfYWRkcoLkSQsKCQoHdGVhbV9p",
            "ZILkSQwKCgoIc2NlbmVfaWQifQoJUmVjb25uZWN0EgoKAmlkGAEgASgJEg0K",
            "BXRva2VuGAIgASgJEhEKCXRpbWVzdGFtcBgDIAEoCRIMCgRoZWFkGAQgASgM",
            "Eg0KBWNhY2hlGAUgASgMOiX440kBguRJCQoHCgV0b2tlboLkSRAKCwoJdGlt",
            "ZXN0YW1wIKwCKjcKDFBsYXllclN0YXR1cxILCgdPZmZsaW5lEAASCgoGT25s",
            "aW5lEAESDgoKRGlzY29ubmVjdBACQiNaAy9wYqoCAlBiyt1JFQgEEgZwbGF5",
            "ZXIaCQgBEAEaA3JpZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Et.VerseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.PlayerStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Player), global::Pb.Player.Parser, new[]{ "Id", "UserId", "Nick", "Hero", "Avatar", "TeamId", "Gender", "Status", "LastSignIn", "LastAddr", "LastGateNode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Reconnect), global::Pb.Reconnect.Parser, new[]{ "Id", "Token", "Timestamp", "Head", "Cache" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PlayerStatus {
    [pbr::OriginalName("Offline")] Offline = 0,
    [pbr::OriginalName("Online")] Online = 1,
    [pbr::OriginalName("Disconnect")] Disconnect = 2,
  }

  #endregion

  #region Messages
  public sealed partial class Player : pb::IMessage<Player>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Player> _parser = new pb::MessageParser<Player>(() => new Player());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Player> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.PlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Player() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Player(Player other) : this() {
      id_ = other.id_;
      userId_ = other.userId_;
      nick_ = other.nick_;
      hero_ = other.hero_;
      avatar_ = other.avatar_;
      teamId_ = other.teamId_;
      gender_ = other.gender_;
      status_ = other.status_;
      lastSignIn_ = other.lastSignIn_;
      lastAddr_ = other.lastAddr_;
      lastGateNode_ = other.lastGateNode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Player Clone() {
      return new Player(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    ///玩家id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 2;
    private string userId_ = "";
    /// <summary>
    ///用户id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nick" field.</summary>
    public const int NickFieldNumber = 3;
    private string nick_ = "";
    /// <summary>
    ///昵称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nick {
      get { return nick_; }
      set {
        nick_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hero" field.</summary>
    public const int HeroFieldNumber = 4;
    private int hero_;
    /// <summary>
    ///玩家英雄角色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Hero {
      get { return hero_; }
      set {
        hero_ = value;
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 5;
    private string avatar_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Avatar {
      get { return avatar_; }
      set {
        avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "teamId" field.</summary>
    public const int TeamIdFieldNumber = 6;
    private string teamId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TeamId {
      get { return teamId_; }
      set {
        teamId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 7;
    private int gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 8;
    private global::Pb.PlayerStatus status_ = global::Pb.PlayerStatus.Offline;
    /// <summary>
    ///玩家状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PlayerStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "lastSignIn" field.</summary>
    public const int LastSignInFieldNumber = 9;
    private long lastSignIn_;
    /// <summary>
    ///最后登录时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastSignIn {
      get { return lastSignIn_; }
      set {
        lastSignIn_ = value;
      }
    }

    /// <summary>Field number for the "lastAddr" field.</summary>
    public const int LastAddrFieldNumber = 10;
    private string lastAddr_ = "";
    /// <summary>
    ///最后登录的地址，重复登录用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastAddr {
      get { return lastAddr_; }
      set {
        lastAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastGateNode" field.</summary>
    public const int LastGateNodeFieldNumber = 11;
    private long lastGateNode_;
    /// <summary>
    ///最后连接的网关节点，重复登录用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastGateNode {
      get { return lastGateNode_; }
      set {
        lastGateNode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Player);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Player other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (UserId != other.UserId) return false;
      if (Nick != other.Nick) return false;
      if (Hero != other.Hero) return false;
      if (Avatar != other.Avatar) return false;
      if (TeamId != other.TeamId) return false;
      if (Gender != other.Gender) return false;
      if (Status != other.Status) return false;
      if (LastSignIn != other.LastSignIn) return false;
      if (LastAddr != other.LastAddr) return false;
      if (LastGateNode != other.LastGateNode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Nick.Length != 0) hash ^= Nick.GetHashCode();
      if (Hero != 0) hash ^= Hero.GetHashCode();
      if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
      if (TeamId.Length != 0) hash ^= TeamId.GetHashCode();
      if (Gender != 0) hash ^= Gender.GetHashCode();
      if (Status != global::Pb.PlayerStatus.Offline) hash ^= Status.GetHashCode();
      if (LastSignIn != 0L) hash ^= LastSignIn.GetHashCode();
      if (LastAddr.Length != 0) hash ^= LastAddr.GetHashCode();
      if (LastGateNode != 0L) hash ^= LastGateNode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (Nick.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nick);
      }
      if (Hero != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hero);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Avatar);
      }
      if (TeamId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TeamId);
      }
      if (Gender != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (Status != global::Pb.PlayerStatus.Offline) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (LastSignIn != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(LastSignIn);
      }
      if (LastAddr.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(LastAddr);
      }
      if (LastGateNode != 0L) {
        output.WriteRawTag(89);
        output.WriteSFixed64(LastGateNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (Nick.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nick);
      }
      if (Hero != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hero);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Avatar);
      }
      if (TeamId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TeamId);
      }
      if (Gender != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (Status != global::Pb.PlayerStatus.Offline) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (LastSignIn != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(LastSignIn);
      }
      if (LastAddr.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(LastAddr);
      }
      if (LastGateNode != 0L) {
        output.WriteRawTag(89);
        output.WriteSFixed64(LastGateNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Nick.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nick);
      }
      if (Hero != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hero);
      }
      if (Avatar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
      }
      if (TeamId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TeamId);
      }
      if (Gender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
      }
      if (Status != global::Pb.PlayerStatus.Offline) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (LastSignIn != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastSignIn);
      }
      if (LastAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastAddr);
      }
      if (LastGateNode != 0L) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Player other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Nick.Length != 0) {
        Nick = other.Nick;
      }
      if (other.Hero != 0) {
        Hero = other.Hero;
      }
      if (other.Avatar.Length != 0) {
        Avatar = other.Avatar;
      }
      if (other.TeamId.Length != 0) {
        TeamId = other.TeamId;
      }
      if (other.Gender != 0) {
        Gender = other.Gender;
      }
      if (other.Status != global::Pb.PlayerStatus.Offline) {
        Status = other.Status;
      }
      if (other.LastSignIn != 0L) {
        LastSignIn = other.LastSignIn;
      }
      if (other.LastAddr.Length != 0) {
        LastAddr = other.LastAddr;
      }
      if (other.LastGateNode != 0L) {
        LastGateNode = other.LastGateNode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
          case 26: {
            Nick = input.ReadString();
            break;
          }
          case 32: {
            Hero = input.ReadInt32();
            break;
          }
          case 42: {
            Avatar = input.ReadString();
            break;
          }
          case 50: {
            TeamId = input.ReadString();
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            Status = (global::Pb.PlayerStatus) input.ReadEnum();
            break;
          }
          case 72: {
            LastSignIn = input.ReadInt64();
            break;
          }
          case 82: {
            LastAddr = input.ReadString();
            break;
          }
          case 89: {
            LastGateNode = input.ReadSFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
          case 26: {
            Nick = input.ReadString();
            break;
          }
          case 32: {
            Hero = input.ReadInt32();
            break;
          }
          case 42: {
            Avatar = input.ReadString();
            break;
          }
          case 50: {
            TeamId = input.ReadString();
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            Status = (global::Pb.PlayerStatus) input.ReadEnum();
            break;
          }
          case 72: {
            LastSignIn = input.ReadInt64();
            break;
          }
          case 82: {
            LastAddr = input.ReadString();
            break;
          }
          case 89: {
            LastGateNode = input.ReadSFixed64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///重连用，可以挪到redis
  /// </summary>
  public sealed partial class Reconnect : pb::IMessage<Reconnect>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Reconnect> _parser = new pb::MessageParser<Reconnect>(() => new Reconnect());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Reconnect> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.PlayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reconnect() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reconnect(Reconnect other) : this() {
      id_ = other.id_;
      token_ = other.token_;
      timestamp_ = other.timestamp_;
      head_ = other.head_;
      cache_ = other.cache_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reconnect Clone() {
      return new Reconnect(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    ///player id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 2;
    private string token_ = "";
    /// <summary>
    ///账号服给的token
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private string timestamp_ = "";
    /// <summary>
    ///断线的时间戳,必须使用MongoDB的格式
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "head" field.</summary>
    public const int HeadFieldNumber = 4;
    private pb::ByteString head_ = pb::ByteString.Empty;
    /// <summary>
    ///gate的Head
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Head {
      get { return head_; }
      set {
        head_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cache" field.</summary>
    public const int CacheFieldNumber = 5;
    private pb::ByteString cache_ = pb::ByteString.Empty;
    /// <summary>
    ///gate的Cache
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Cache {
      get { return cache_; }
      set {
        cache_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Reconnect);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Reconnect other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Token != other.Token) return false;
      if (Timestamp != other.Timestamp) return false;
      if (Head != other.Head) return false;
      if (Cache != other.Cache) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
      if (Head.Length != 0) hash ^= Head.GetHashCode();
      if (Cache.Length != 0) hash ^= Cache.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Timestamp);
      }
      if (Head.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Head);
      }
      if (Cache.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Cache);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Timestamp);
      }
      if (Head.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Head);
      }
      if (Cache.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Cache);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (Timestamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
      }
      if (Head.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Head);
      }
      if (Cache.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Cache);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Reconnect other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.Timestamp.Length != 0) {
        Timestamp = other.Timestamp;
      }
      if (other.Head.Length != 0) {
        Head = other.Head;
      }
      if (other.Cache.Length != 0) {
        Cache = other.Cache;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
          case 26: {
            Timestamp = input.ReadString();
            break;
          }
          case 34: {
            Head = input.ReadBytes();
            break;
          }
          case 42: {
            Cache = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
          case 26: {
            Timestamp = input.ReadString();
            break;
          }
          case 34: {
            Head = input.ReadBytes();
            break;
          }
          case 42: {
            Cache = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
