// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: 15m.games/kiwi_tool/kiwi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Et {

  /// <summary>Holder for reflection information generated from 15m.games/kiwi_tool/kiwi.proto</summary>
  public static partial class VerseReflection {

    #region Descriptor
    /// <summary>File descriptor for 15m.games/kiwi_tool/kiwi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VerseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChoxNW0uZ2FtZXMvdG9vbC92ZXJzZS5wcm90bxICZXQaIGdvb2dsZS9wcm90",
            "b2J1Zi9kZXNjcmlwdG9yLnByb3RvIi4KA050YxILCgNzdmMYASABKAkSGgoF",
            "aXRlbXMYAiADKAsyCy5ldC5OdGNJdGVtIl4KB050Y0l0ZW0SDAoEY29kZRgB",
            "IAEoCRIbCgZ3b3JrZXIYAiABKA4yCy5ldC5FV29ya2VyEhsKBm9yaWdpbhgD",
            "IAEoDjILLmV0LkVPcmlnaW4SCwoDa2V5GAQgASgJIlEKA1N2YxIKCgJpZBgB",
            "IAEoBRIMCgRuYW1lGAIgASgJEhoKBndvcmtlchgDIAEoCzIKLmV0Lldvcmtl",
            "chIUCgNudGMYBCADKAsyBy5ldC5OdGMiTwoGV29ya2VyEhsKBndvcmtlchgB",
            "IAEoDjILLmV0LkVXb3JrZXISGwoGb3JpZ2luGAIgASgOMgsuZXQuRU9yaWdp",
            "bhILCgNrZXkYAyABKAkiLgoERmFpbBIMCgRjb2RlGAEgASgFEgsKA2tleRgC",
            "IAEoCRILCgNtc2cYAyABKAkiMAoISWR4RmllbGQSDAoEbmFtZRgBIAEoCRIW",
            "CgR0eXBlGAIgASgOMgguZXQuRUlkeCJeCgNJZHgSHAoGZmllbGRzGAEgAygL",
            "MgwuZXQuSWR4RmllbGQSDgoGdW5pcXVlGAIgASgIEgwKBG5hbWUYAyABKAkS",
            "CwoDdHRsGAQgASgDEg4KBnNwYXJzZRgFIAEoCCopCgdFT3JpZ2luEgcKA1Br",
            "dBAAEggKBEhlYWQQARILCgdTZXJ2aWNlEAIqPgoHRVdvcmtlchIGCgJHbxAA",
            "EgoKBkFjdGl2ZRABEgkKBVNoYXJlEAISCgoGR2xvYmFsEAMSCAoEU2VsZhAE",
            "KjMKBEVJZHgSBwoDQXNjEAASCAoERGVzYxABEg4KClR3b0RTcGhlcmUQAhII",
            "CgRUZXh0EAM6NAoDc3ZjEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25z",
            "GNmbCSABKAsyBy5ldC5TdmM6LwoEY29kZRIfLmdvb2dsZS5wcm90b2J1Zi5N",
            "ZXNzYWdlT3B0aW9ucxi8nAkgASgFOi8KBHJvbGUSHy5nb29nbGUucHJvdG9i",
            "dWYuTWVzc2FnZU9wdGlvbnMYvZwJIAMoCTo5CgRmYWlsEh8uZ29vZ2xlLnBy",
            "b3RvYnVmLk1lc3NhZ2VPcHRpb25zGL6cCSADKAsyCC5ldC5GYWlsOjEKBnNj",
            "aGVtZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxi/nAkgASgI",
            "OjcKA2lkeBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjAnAkg",
            "AygLMgcuZXQuSWR4Oj0KBndvcmtlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNz",
            "YWdlT3B0aW9ucxjBnAkgASgLMgouZXQuV29ya2VyOjEKCHJlcXVpcmVkEh0u",
            "Z29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxignQkgASgIOi4KBXJlZ2V4",
            "Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxihnQkgASgJOi4KBWx0",
            "XzMyEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxiinQkgASgFOi4K",
            "BWd0XzMyEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxijnQkgASgF",
            "Oi4KBWx0XzY0Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxiknQkg",
            "ASgFOi4KBWd0XzY0Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxil",
            "nQkgASgFOi8KBmx0X2YzMhIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlv",
            "bnMYpp0JIAEoDzovCgZndF9mMzISHS5nb29nbGUucHJvdG9idWYuRmllbGRP",
            "cHRpb25zGKedCSABKA86LwoGbHRfZjY0Eh0uZ29vZ2xlLnByb3RvYnVmLkZp",
            "ZWxkT3B0aW9ucxionQkgASgQOi8KBmd0X2Y2NBIdLmdvb2dsZS5wcm90b2J1",
            "Zi5GaWVsZE9wdGlvbnMYqZ0JIAEoEDovCgZsdF9mbHQSHS5nb29nbGUucHJv",
            "dG9idWYuRmllbGRPcHRpb25zGKqdCSABKAI6MAoHbHRlX2ZsdBIdLmdvb2ds",
            "ZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYq50JIAEoAjovCgZndF9mbHQSHS5n",
            "b29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGKydCSABKAI6MAoHZ3RlX2Zs",
            "dBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYrZ0JIAEoAjovCgZs",
            "dF9kYmwSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGK6dCSABKAE6",
            "MAoHbHRlX2RibBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYr50J",
            "IAEoATovCgZndF9kYmwSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25z",
            "GLCdCSABKAE6MAoHZ3RlX2RibBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9w",
            "dGlvbnMYsZ0JIAEoAToyCglyZXBlYXRfbHQSHS5nb29nbGUucHJvdG9idWYu",
            "RmllbGRPcHRpb25zGLKdCSABKAU6MgoJcmVwZWF0X2VxEh0uZ29vZ2xlLnBy",
            "b3RvYnVmLkZpZWxkT3B0aW9ucxiznQkgASgFOjIKCXJlcGVhdF9ndBIdLmdv",
            "b2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYtJ0JIAEoBTozCgpzdHJfbGVu",
            "X2x0Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxi1nQkgASgFOjMK",
            "CnN0cl9sZW5fZXESHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGLad",
            "CSABKAU6MwoKc3RyX2xlbl9ndBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9w",
            "dGlvbnMYt50JIAEoBUIQWg4xNW0uZ2FtZXMvdG9vbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Et.EOrigin), typeof(global::Et.EWorker), typeof(global::Et.EIdx), }, new pb::Extension[] { VerseExtensions.Svc, VerseExtensions.Code, VerseExtensions.Role, VerseExtensions.Fail, VerseExtensions.Scheme, VerseExtensions.Idx, VerseExtensions.Worker, VerseExtensions.Required, VerseExtensions.Regex, VerseExtensions.Lt32, VerseExtensions.Gt32, VerseExtensions.Lt64, VerseExtensions.Gt64, VerseExtensions.LtF32, VerseExtensions.GtF32, VerseExtensions.LtF64, VerseExtensions.GtF64, VerseExtensions.LtFlt, VerseExtensions.LteFlt, VerseExtensions.GtFlt, VerseExtensions.GteFlt, VerseExtensions.LtDbl, VerseExtensions.LteDbl, VerseExtensions.GtDbl, VerseExtensions.GteDbl, VerseExtensions.RepeatLt, VerseExtensions.RepeatEq, VerseExtensions.RepeatGt, VerseExtensions.StrLenLt, VerseExtensions.StrLenEq, VerseExtensions.StrLenGt }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.Ntc), global::Et.Ntc.Parser, new[]{ "Svc", "Items" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.NtcItem), global::Et.NtcItem.Parser, new[]{ "Code", "Worker", "Origin", "Key" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.Svc), global::Et.Svc.Parser, new[]{ "Id", "Name", "Worker", "Ntc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.Worker), global::Et.Worker.Parser, new[]{ "Worker_", "Origin", "Key" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.Fail), global::Et.Fail.Parser, new[]{ "Code", "Key", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.IdxField), global::Et.IdxField.Parser, new[]{ "Name", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Et.Idx), global::Et.Idx.Parser, new[]{ "Fields", "Unique", "Name", "Ttl", "Sparse" }, null, null, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of 15m.games/kiwi_tool/kiwi.proto</summary>
  public static partial class VerseExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Et.Svc> Svc =
      new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Et.Svc>(151001, pb::FieldCodec.ForMessage(1208010, global::Et.Svc.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> Code =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(151100, pb::FieldCodec.ForInt32(1208800, 0));
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, string> Role =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, string>(151101, pb::FieldCodec.ForString(1208810));
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, global::Et.Fail> Fail =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, global::Et.Fail>(151102, pb::FieldCodec.ForMessage(1208818, global::Et.Fail.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> Scheme =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(151103, pb::FieldCodec.ForBool(1208824, false));
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, global::Et.Idx> Idx =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, global::Et.Idx>(151104, pb::FieldCodec.ForMessage(1208834, global::Et.Idx.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Et.Worker> Worker =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Et.Worker>(151105, pb::FieldCodec.ForMessage(1208842, global::Et.Worker.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> Required =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(151200, pb::FieldCodec.ForBool(1209600, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Regex =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(151201, pb::FieldCodec.ForString(1209610, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> Lt32 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151202, pb::FieldCodec.ForInt32(1209616, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> Gt32 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151203, pb::FieldCodec.ForInt32(1209624, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> Lt64 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151204, pb::FieldCodec.ForInt32(1209632, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> Gt64 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151205, pb::FieldCodec.ForInt32(1209640, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> LtF32 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151206, pb::FieldCodec.ForSFixed32(1209653, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> GtF32 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151207, pb::FieldCodec.ForSFixed32(1209661, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, long> LtF64 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, long>(151208, pb::FieldCodec.ForSFixed64(1209665, 0L));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, long> GtF64 =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, long>(151209, pb::FieldCodec.ForSFixed64(1209673, 0L));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float> LtFlt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float>(151210, pb::FieldCodec.ForFloat(1209685, 0F));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float> LteFlt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float>(151211, pb::FieldCodec.ForFloat(1209693, 0F));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float> GtFlt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float>(151212, pb::FieldCodec.ForFloat(1209701, 0F));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float> GteFlt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float>(151213, pb::FieldCodec.ForFloat(1209709, 0F));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double> LtDbl =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double>(151214, pb::FieldCodec.ForDouble(1209713, 0D));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double> LteDbl =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double>(151215, pb::FieldCodec.ForDouble(1209721, 0D));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double> GtDbl =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double>(151216, pb::FieldCodec.ForDouble(1209729, 0D));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double> GteDbl =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, double>(151217, pb::FieldCodec.ForDouble(1209737, 0D));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> RepeatLt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151218, pb::FieldCodec.ForInt32(1209744, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> RepeatEq =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151219, pb::FieldCodec.ForInt32(1209752, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> RepeatGt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151220, pb::FieldCodec.ForInt32(1209760, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> StrLenLt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151221, pb::FieldCodec.ForInt32(1209768, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> StrLenEq =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151222, pb::FieldCodec.ForInt32(1209776, 0));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> StrLenGt =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(151223, pb::FieldCodec.ForInt32(1209784, 0));
  }

  #region Enums
  public enum EOrigin {
    [pbr::OriginalName("Pkt")] Pkt = 0,
    [pbr::OriginalName("Head")] Head = 1,
    [pbr::OriginalName("Service")] Service = 2,
  }

  public enum EWorker {
    [pbr::OriginalName("Go")] Go = 0,
    /// <summary>
    ///需要key
    /// </summary>
    [pbr::OriginalName("Active")] Active = 1,
    /// <summary>
    ///需要key
    /// </summary>
    [pbr::OriginalName("Share")] Share = 2,
    [pbr::OriginalName("Global")] Global = 3,
    [pbr::OriginalName("Self")] Self = 4,
  }

  public enum EIdx {
    [pbr::OriginalName("Asc")] Asc = 0,
    [pbr::OriginalName("Desc")] Desc = 1,
    [pbr::OriginalName("TwoDSphere")] TwoDsphere = 2,
    [pbr::OriginalName("Text")] Text = 3,
  }

  #endregion

  #region Messages
  public sealed partial class Ntc : pb::IMessage<Ntc>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ntc> _parser = new pb::MessageParser<Ntc>(() => new Ntc());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ntc> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ntc() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ntc(Ntc other) : this() {
      svc_ = other.svc_;
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ntc Clone() {
      return new Ntc(this);
    }

    /// <summary>Field number for the "svc" field.</summary>
    public const int SvcFieldNumber = 1;
    private string svc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Svc {
      get { return svc_; }
      set {
        svc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Et.NtcItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(18, global::Et.NtcItem.Parser);
    private readonly pbc::RepeatedField<global::Et.NtcItem> items_ = new pbc::RepeatedField<global::Et.NtcItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Et.NtcItem> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ntc);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ntc other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Svc != other.Svc) return false;
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Svc.Length != 0) hash ^= Svc.GetHashCode();
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Svc.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Svc);
      }
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Svc.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Svc);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Svc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Svc);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ntc other) {
      if (other == null) {
        return;
      }
      if (other.Svc.Length != 0) {
        Svc = other.Svc;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Svc = input.ReadString();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Svc = input.ReadString();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NtcItem : pb::IMessage<NtcItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NtcItem> _parser = new pb::MessageParser<NtcItem>(() => new NtcItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NtcItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NtcItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NtcItem(NtcItem other) : this() {
      code_ = other.code_;
      worker_ = other.worker_;
      origin_ = other.origin_;
      key_ = other.key_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NtcItem Clone() {
      return new NtcItem(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private string code_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Code {
      get { return code_; }
      set {
        code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "worker" field.</summary>
    public const int WorkerFieldNumber = 2;
    private global::Et.EWorker worker_ = global::Et.EWorker.Go;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Et.EWorker Worker {
      get { return worker_; }
      set {
        worker_ = value;
      }
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 3;
    private global::Et.EOrigin origin_ = global::Et.EOrigin.Pkt;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Et.EOrigin Origin {
      get { return origin_; }
      set {
        origin_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 4;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NtcItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NtcItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Worker != other.Worker) return false;
      if (Origin != other.Origin) return false;
      if (Key != other.Key) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code.Length != 0) hash ^= Code.GetHashCode();
      if (Worker != global::Et.EWorker.Go) hash ^= Worker.GetHashCode();
      if (Origin != global::Et.EOrigin.Pkt) hash ^= Origin.GetHashCode();
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Code);
      }
      if (Worker != global::Et.EWorker.Go) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Worker);
      }
      if (Origin != global::Et.EOrigin.Pkt) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Origin);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Code);
      }
      if (Worker != global::Et.EWorker.Go) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Worker);
      }
      if (Origin != global::Et.EOrigin.Pkt) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Origin);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Code);
      }
      if (Worker != global::Et.EWorker.Go) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Worker);
      }
      if (Origin != global::Et.EOrigin.Pkt) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Origin);
      }
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NtcItem other) {
      if (other == null) {
        return;
      }
      if (other.Code.Length != 0) {
        Code = other.Code;
      }
      if (other.Worker != global::Et.EWorker.Go) {
        Worker = other.Worker;
      }
      if (other.Origin != global::Et.EOrigin.Pkt) {
        Origin = other.Origin;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Code = input.ReadString();
            break;
          }
          case 16: {
            Worker = (global::Et.EWorker) input.ReadEnum();
            break;
          }
          case 24: {
            Origin = (global::Et.EOrigin) input.ReadEnum();
            break;
          }
          case 34: {
            Key = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Code = input.ReadString();
            break;
          }
          case 16: {
            Worker = (global::Et.EWorker) input.ReadEnum();
            break;
          }
          case 24: {
            Origin = (global::Et.EOrigin) input.ReadEnum();
            break;
          }
          case 34: {
            Key = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Svc : pb::IMessage<Svc>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Svc> _parser = new pb::MessageParser<Svc>(() => new Svc());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Svc> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Svc() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Svc(Svc other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      worker_ = other.worker_ != null ? other.worker_.Clone() : null;
      ntc_ = other.ntc_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Svc Clone() {
      return new Svc(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "worker" field.</summary>
    public const int WorkerFieldNumber = 3;
    private global::Et.Worker worker_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Et.Worker Worker {
      get { return worker_; }
      set {
        worker_ = value;
      }
    }

    /// <summary>Field number for the "ntc" field.</summary>
    public const int NtcFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Et.Ntc> _repeated_ntc_codec
        = pb::FieldCodec.ForMessage(34, global::Et.Ntc.Parser);
    private readonly pbc::RepeatedField<global::Et.Ntc> ntc_ = new pbc::RepeatedField<global::Et.Ntc>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Et.Ntc> Ntc {
      get { return ntc_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Svc);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Svc other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Worker, other.Worker)) return false;
      if(!ntc_.Equals(other.ntc_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (worker_ != null) hash ^= Worker.GetHashCode();
      hash ^= ntc_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (worker_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Worker);
      }
      ntc_.WriteTo(output, _repeated_ntc_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (worker_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Worker);
      }
      ntc_.WriteTo(ref output, _repeated_ntc_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (worker_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Worker);
      }
      size += ntc_.CalculateSize(_repeated_ntc_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Svc other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.worker_ != null) {
        if (worker_ == null) {
          Worker = new global::Et.Worker();
        }
        Worker.MergeFrom(other.Worker);
      }
      ntc_.Add(other.ntc_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (worker_ == null) {
              Worker = new global::Et.Worker();
            }
            input.ReadMessage(Worker);
            break;
          }
          case 34: {
            ntc_.AddEntriesFrom(input, _repeated_ntc_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (worker_ == null) {
              Worker = new global::Et.Worker();
            }
            input.ReadMessage(Worker);
            break;
          }
          case 34: {
            ntc_.AddEntriesFrom(ref input, _repeated_ntc_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Worker : pb::IMessage<Worker>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Worker> _parser = new pb::MessageParser<Worker>(() => new Worker());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Worker> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Worker() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Worker(Worker other) : this() {
      worker_ = other.worker_;
      origin_ = other.origin_;
      key_ = other.key_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Worker Clone() {
      return new Worker(this);
    }

    /// <summary>Field number for the "worker" field.</summary>
    public const int Worker_FieldNumber = 1;
    private global::Et.EWorker worker_ = global::Et.EWorker.Go;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Et.EWorker Worker_ {
      get { return worker_; }
      set {
        worker_ = value;
      }
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 2;
    private global::Et.EOrigin origin_ = global::Et.EOrigin.Pkt;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Et.EOrigin Origin {
      get { return origin_; }
      set {
        origin_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 3;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Worker);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Worker other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Worker_ != other.Worker_) return false;
      if (Origin != other.Origin) return false;
      if (Key != other.Key) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Worker_ != global::Et.EWorker.Go) hash ^= Worker_.GetHashCode();
      if (Origin != global::Et.EOrigin.Pkt) hash ^= Origin.GetHashCode();
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Worker_ != global::Et.EWorker.Go) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Worker_);
      }
      if (Origin != global::Et.EOrigin.Pkt) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Origin);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Worker_ != global::Et.EWorker.Go) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Worker_);
      }
      if (Origin != global::Et.EOrigin.Pkt) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Origin);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Worker_ != global::Et.EWorker.Go) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Worker_);
      }
      if (Origin != global::Et.EOrigin.Pkt) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Origin);
      }
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Worker other) {
      if (other == null) {
        return;
      }
      if (other.Worker_ != global::Et.EWorker.Go) {
        Worker_ = other.Worker_;
      }
      if (other.Origin != global::Et.EOrigin.Pkt) {
        Origin = other.Origin;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Worker_ = (global::Et.EWorker) input.ReadEnum();
            break;
          }
          case 16: {
            Origin = (global::Et.EOrigin) input.ReadEnum();
            break;
          }
          case 26: {
            Key = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Worker_ = (global::Et.EWorker) input.ReadEnum();
            break;
          }
          case 16: {
            Origin = (global::Et.EOrigin) input.ReadEnum();
            break;
          }
          case 26: {
            Key = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Fail : pb::IMessage<Fail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Fail> _parser = new pb::MessageParser<Fail>(() => new Fail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Fail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fail(Fail other) : this() {
      code_ = other.code_;
      key_ = other.key_;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fail Clone() {
      return new Fail(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 2;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Fail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Fail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Key != other.Key) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Key);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Key.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Key);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Fail other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Key = input.ReadString();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Key = input.ReadString();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class IdxField : pb::IMessage<IdxField>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IdxField> _parser = new pb::MessageParser<IdxField>(() => new IdxField());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IdxField> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IdxField() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IdxField(IdxField other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IdxField Clone() {
      return new IdxField(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Et.EIdx type_ = global::Et.EIdx.Asc;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Et.EIdx Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IdxField);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IdxField other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != global::Et.EIdx.Asc) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::Et.EIdx.Asc) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::Et.EIdx.Asc) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != global::Et.EIdx.Asc) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IdxField other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != global::Et.EIdx.Asc) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Et.EIdx) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Et.EIdx) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Idx : pb::IMessage<Idx>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Idx> _parser = new pb::MessageParser<Idx>(() => new Idx());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Idx> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Et.VerseReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Idx() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Idx(Idx other) : this() {
      fields_ = other.fields_.Clone();
      unique_ = other.unique_;
      name_ = other.name_;
      ttl_ = other.ttl_;
      sparse_ = other.sparse_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Idx Clone() {
      return new Idx(this);
    }

    /// <summary>Field number for the "fields" field.</summary>
    public const int FieldsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Et.IdxField> _repeated_fields_codec
        = pb::FieldCodec.ForMessage(10, global::Et.IdxField.Parser);
    private readonly pbc::RepeatedField<global::Et.IdxField> fields_ = new pbc::RepeatedField<global::Et.IdxField>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Et.IdxField> Fields {
      get { return fields_; }
    }

    /// <summary>Field number for the "unique" field.</summary>
    public const int UniqueFieldNumber = 2;
    private bool unique_;
    /// <summary>
    ///唯一索引
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unique {
      get { return unique_; }
      set {
        unique_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    ///索引名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ttl" field.</summary>
    public const int TtlFieldNumber = 4;
    private long ttl_;
    /// <summary>
    ///用于在一定时间后或在特定的时刻自动从集合中删除文档
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Ttl {
      get { return ttl_; }
      set {
        ttl_ = value;
      }
    }

    /// <summary>Field number for the "sparse" field.</summary>
    public const int SparseFieldNumber = 5;
    private bool sparse_;
    /// <summary>
    ///稀疏索引仅包含具有索引字段的文档条目，即使索引字段包含空值也是如此。索引会跳过任何缺少索引字段的文档
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Sparse {
      get { return sparse_; }
      set {
        sparse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Idx);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Idx other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!fields_.Equals(other.fields_)) return false;
      if (Unique != other.Unique) return false;
      if (Name != other.Name) return false;
      if (Ttl != other.Ttl) return false;
      if (Sparse != other.Sparse) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= fields_.GetHashCode();
      if (Unique != false) hash ^= Unique.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Ttl != 0L) hash ^= Ttl.GetHashCode();
      if (Sparse != false) hash ^= Sparse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      fields_.WriteTo(output, _repeated_fields_codec);
      if (Unique != false) {
        output.WriteRawTag(16);
        output.WriteBool(Unique);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Ttl != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Ttl);
      }
      if (Sparse != false) {
        output.WriteRawTag(40);
        output.WriteBool(Sparse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      fields_.WriteTo(ref output, _repeated_fields_codec);
      if (Unique != false) {
        output.WriteRawTag(16);
        output.WriteBool(Unique);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Ttl != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Ttl);
      }
      if (Sparse != false) {
        output.WriteRawTag(40);
        output.WriteBool(Sparse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += fields_.CalculateSize(_repeated_fields_codec);
      if (Unique != false) {
        size += 1 + 1;
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Ttl != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Ttl);
      }
      if (Sparse != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Idx other) {
      if (other == null) {
        return;
      }
      fields_.Add(other.fields_);
      if (other.Unique != false) {
        Unique = other.Unique;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Ttl != 0L) {
        Ttl = other.Ttl;
      }
      if (other.Sparse != false) {
        Sparse = other.Sparse;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            fields_.AddEntriesFrom(input, _repeated_fields_codec);
            break;
          }
          case 16: {
            Unique = input.ReadBool();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            Ttl = input.ReadInt64();
            break;
          }
          case 40: {
            Sparse = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            fields_.AddEntriesFrom(ref input, _repeated_fields_codec);
            break;
          }
          case 16: {
            Unique = input.ReadBool();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            Ttl = input.ReadInt64();
            break;
          }
          case 40: {
            Sparse = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
